language: php

php:
  - 7.2

sudo: false

services:
  - mysql

before_script:
  - composer install
  - composer dump-autoload
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate

script: phpunit
