web:
    image: hitalos/laravel
    ports:
        - 7000:80
    volumes:
        - ./:/var/www
    links:
        - db
    environment:
        DB_HOST: db
        DB_DATABASE: dbname
        DB_USERNAME: username
        DB_PASSWORD: p455w0rd
        DB_CONNECTION: mysql
db:
    image: mysql:5.7
    environment:
        # with mysql
        MYSQL_DATABASE: dbname
        MYSQL_USER: ROOT
        MYSQL_ROOT_PASSWORD: p455w0rd
